#!/bin/sh

findarmgcc () {
	for pth in `echo $PATH | sed 's/:/ /g'`; do
		for gcc in $pth/arm-linux-gnueabi-gcc*; do
			cat <<END > test-gcc.c
int main() {}
END
			if $gcc test-gcc.c -o /dev/null > /dev/null 2>&1; then
				echo $gcc
				rm test-gcc.c
				exit 0
			fi
			rm test-gcc.c
		done
	done
	exit 1
}
missing () {
	echo "Missing program $1." 1>&2
	if [ -n "$2" ]; then
		echo "It should have gotten installed together with $2."
	fi
	exit 1
}
check () {
	which sed || missing sed
	which abootimg || missing abootimg
	which abootimg-pack-initrd || missing abootimg-pack-initrd abootimg
	which tar || missing tar
}
checkgcc () {
	if [ -z "$1" ]; then
		echo "Could not find a GCC compiler for arm-linux-gnueabi."
		exit 1
	fi
}
$@
