#!/bin/sh
	
CROSS_COMPILE=${2:-arm*-linux-gnueabihf*}

missing () {
	echo "Missing program $1." 1>&2
	if [ "$2" ]; then
		echo "Please install $2." 1>&2
	fi
	exit 1
}
check () {
	which sed || missing sed
	which abootimg || missing abootimg
	which tar || missing tar
	which debuild || missing debuild devscripts
	which debootstrap || missing debootstrap
}
checkgcc () {
	gcc="arm-linux-gnueabihf-gcc"
	cat <<END > test-gcc.c
int main() {}
END
	if $gcc test-gcc.c -o /dev/null > /dev/null 2>&1; then
		rm test-gcc.c
		exit 0
	fi
	rm test-gcc.c
	echo "Could not find a GCC compiler for $CROSS_COMPILE."
	exit 1
}
$@
