#!/sbin/sh
export PATH=/sbin
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
mount -t ext4 /dev/mmcblk0p32 /data
mount -t ext4 /dev/mmcblk1p2 /root >> /data/bananian.log
mount -t devtmpfs devtmpfs /root/dev >> /data/bananian.log
mount -t sysfs sysfs /root/sys >> /data/bananian.log
mount -t procfs procfs /root/proc >> /data/bananian.log
echo 'Mounted root' >> /data/bananian.log
exec run-init /root /sbin/init $@
