#!/bin/sh
# Copyright (C) 2020-2021 Affe Null <affenull2345@gmail.com>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
	
missing () {
	echo "Missing program $1." 1>&2
	if [ -n "$2" ]; then
		echo "Please install $2." 1>&2
	fi
	exit 1
}

warn () {
	echo "Warning: $1" 1>&2
}

deps () {
	which abootimg || missing abootimg
	which tar || missing tar
	which debootstrap || missing debootstrap
	which pdebuild || warn "Program pdebuild is required for building from source."
	which wget || missing wget
	which git-deborig || missing git-deborig
}
root () {
	if [ "x`id -u`" != x0 ]; then
		echo "You are not running as root."
		exit 1
	fi
}

$@
