#!/bin/sh
# Copyright (C) 2020-2021 Affe Null <affenull2345@gmail.com>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

which qemu-arm-static || \
	"`dirname $0`/check" missing qemu-arm-static qemu-user-static

trap "umount debroot/dev debroot/proc debroot/sys" EXIT
trap "exit 2" INT TERM

mount -o bind /dev debroot/dev
mount -o bind /proc debroot/proc
mount -o bind /sys debroot/sys
chroot debroot /bin/sh -c 'debootstrap/debootstrap --second-stage; cd /var/cache && dpkg -i *.deb && rm -f *.deb && adduser --gecos "Bananian User" user && adduser user sudo'
