#!/bin/sh
set -e
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/fwload" ]; then
		update-rc.d fwload defaults >/dev/null
		invoke-rc.d fwload start
	fi
fi
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/wifi" ]; then
		update-rc.d wifi defaults >/dev/null
		invoke-rc.d wifi start
	fi
fi
#DEBHELPER#
