#!/bin/sh
set -e
if [ "$1" = "purge" ] ; then
	update-rc.d fwmount remove >/dev/null
fi
if [ "$1" = "purge" ] ; then
	update-rc.d usb remove >/dev/null
fi
if [ "$1" = "purge" ] ; then
	update-rc.d wifi remove >/dev/null
fi
#DEBHELPER#
