#!/bin/sh
set -e
if [ -x "/etc/init.d/fwmount" ]; then
	invoke-rc.d fwmount stop
fi
if [ -x "/etc/init.d/usb" ]; then
	invoke-rc.d usb stop
fi
if [ -x "/etc/init.d/wifi" ]; then
	invoke-rc.d wifi stop
fi
#DEBHELPER#
